-- Create investment_reports table
CREATE TABLE IF NOT EXISTS public.investment_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  ticker TEXT NOT NULL,
  company_name TEXT NOT NULL,
  verdict TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 50,
  summary TEXT NOT NULL,
  report_text TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.investment_reports ENABLE ROW LEVEL SECURITY;

-- Select Policy (read access)
CREATE POLICY "Users can select their own reports"
ON public.investment_reports
FOR SELECT
TO authenticated
USING ( (select auth.uid()) = user_id );

-- Insert Policy (write access)
CREATE POLICY "Users can insert their own reports"
ON public.investment_reports
FOR INSERT
TO authenticated
WITH CHECK ( (select auth.uid()) = user_id );

-- Delete Policy (delete access)
CREATE POLICY "Users can delete their own reports"
ON public.investment_reports
FOR DELETE
TO authenticated
USING ( (select auth.uid()) = user_id );


-- Create todos table (requested in sample page.tsx)
CREATE TABLE IF NOT EXISTS public.todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_complete BOOLEAN NOT NULL DEFAULT false,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for todos
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- Allow read access for todos (modify if you want users to only see their own)
CREATE POLICY "Allow public read access for todos"
ON public.todos
FOR SELECT
TO anon, authenticated
USING ( true );
