import { getGeminiFlash, callGemini } from '../../services/gemini.js'

const REPORT_PROMPT = `You are a senior equity research analyst. Write a professional investment report in markdown format.

Structure:
# [Company Name] — Investment Report

## Executive Summary
(3-4 sentences: recommendation, confidence, and thesis)

## Company Overview
(Business, products, moat)

## Financial Analysis
(Revenue growth, margins, balance sheet, valuation)

## News & Sentiment
(Recent developments and market impact)

## Risk Assessment
(Top risks with severity)

## Competitive Landscape
(Market position vs peers)

## Growth Outlook
(Catalysts, TAM, long-term)

## Investment Decision
(Recommendation with bull/bear case)

---
*Generated by AlphaLens AI Research Agent*

Be specific with numbers. Reference the data provided. Professional tone.`

export async function reportGeneratorNode(state, config) {
  const { company, companyData, financialData, newsData, riskData, competitorData, growthData, decisionData } = state
  const onProgress = config?.configurable?.onProgress

  onProgress?.({ agent: 'report', status: 'running', message: 'Generating report...' })

  try {
    const context = `
Company: ${companyData?.name || company} (${companyData?.ticker || ''})
Recommendation: ${decisionData?.recommendation || 'N/A'} — Confidence: ${decisionData?.confidence || 0}%

Scores: Financial=${decisionData?.scores?.financial || 'N/A'}, Growth=${decisionData?.scores?.growth || 'N/A'}, Sentiment=${decisionData?.scores?.sentiment || 'N/A'}, Moat=${decisionData?.scores?.moat || 'N/A'}, Risk=${decisionData?.scores?.risk || 'N/A'}, Valuation=${decisionData?.scores?.valuation || 'N/A'}, Overall=${decisionData?.scores?.overall || 'N/A'}

Business: ${companyData?.businessSummary || ''}
Products: ${companyData?.products?.join(', ') || ''}
Moat: ${companyData?.moat || ''}

Financial Health: ${financialData?.healthGrade || ''} (${financialData?.healthScore || 0}/100) — ${financialData?.healthReason || ''}
Revenue Growth: ${financialData?.revenueGrowth != null ? financialData.revenueGrowth.toFixed(1) + '%' : 'N/A'}
Gross Margin: ${financialData?.grossMargin != null ? financialData.grossMargin.toFixed(1) + '%' : 'N/A'}
Net Margin: ${financialData?.netMargin != null ? financialData.netMargin.toFixed(1) + '%' : 'N/A'}
P/E: ${financialData?.trailingPE || 'N/A'} trailing, ${financialData?.forwardPE || 'N/A'} forward

News: ${newsData?.summary || ''}
Risk Level: ${riskData?.overallRisk || ''} (${riskData?.riskScore || 0}/100) — ${riskData?.riskSummary || ''}
Competitive Position: ${competitorData?.competitivePosition || ''}
Growth: ${growthData?.growthOutlook || ''} — ${growthData?.growthSummary || ''}
Catalysts: ${growthData?.catalysts?.join('; ') || ''}

Investment Thesis: ${decisionData?.reasoning || ''}
Bull Case: ${decisionData?.keyBullets?.bullCase?.join('; ') || ''}
Bear Case: ${decisionData?.keyBullets?.bearCase?.join('; ') || ''}
Time Horizon: ${decisionData?.timeHorizon || '12 months'}
`

    const llm = getGeminiFlash()
    const report = await callGemini(llm, REPORT_PROMPT, context)

    onProgress?.({ agent: 'report', status: 'done', message: 'Report generated' })

    return { report }
  } catch (err) {
    onProgress?.({ agent: 'report', status: 'error', message: err.message })
    return {
      report: `# ${company} Investment Report\n\nReport generation failed: ${err.message}`,
      errors: [`Report: ${err.message}`],
    }
  }
}
