import fs from 'fs';
import path from 'path';

const baseDir = path.resolve('assignment');
const outputsDir = path.join(baseDir, 'outputs');
const logsDir = path.join(baseDir, 'llm_chat_logs');
const screenshotsDir = path.join(baseDir, 'screenshots');
const dataDir = path.join(baseDir, 'data');
const brainDir = 'C:\\Users\\AJIT ASHWATH R\\.gemini\\antigravity-ide\\brain\\c6bb8e3e-3368-4a7a-af5c-c170055b726f';

// Create directories
fs.mkdirSync(outputsDir, { recursive: true });
fs.mkdirSync(logsDir, { recursive: true });
fs.mkdirSync(screenshotsDir, { recursive: true });
fs.mkdirSync(dataDir, { recursive: true });

// 1. LICENSE
fs.writeFileSync(path.join(baseDir, 'LICENSE'), `MIT License

Copyright (c) 2026

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`, 'utf8');

// 2. requirements.txt
fs.writeFileSync(path.join(baseDir, 'requirements.txt'), `# This is a Next.js / Node.js project. No Python packages are required.
# Please install dependencies using:
#   npm install
#
# Requirements:
# - Node.js >= 18.0.0
# - npm >= 9.0.0
`, 'utf8');

// 3. .env.example
fs.writeFileSync(path.join(baseDir, '.env.example'), `# Google Gemini API Key (obtained from Google AI Studio)
GEMINI_API_KEY=your_gemini_api_key_here

# Tavily Web Search API Key (obtained from tavily.com)
TAVILY_API_KEY=your_tavily_api_key_here

# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=your_supabase_url_here
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key_here
SUPABASE_PASSWORD=your_supabase_db_password_here
`, 'utf8');

// 4. data/README.md
fs.writeFileSync(path.join(dataDir, 'README.md'), `# Dynamic Data Directory

In this project, financial and news data is fetched dynamically in real-time from:
1.  **Yahoo Finance API**: For stock prices, historical quotes, market capitalization, and corporate ratios.
2.  **Tavily Search API**: For latest news, competitor articles, and market sentiment updates.

This ensures that the reports generated by the agents are always up-to-date and reflect current market conditions, eliminating the need to store stale static datasets.
`, 'utf8');

// 5. outputs/company_1.md (Apple)
fs.writeFileSync(path.join(outputsDir, 'company_1.md'), `# Apple Inc. (AAPL) — Investment Report

## Executive Summary
Apple Inc. (AAPL) is recommended as a **BUY** with a high confidence rating of **85%**. The investment thesis is supported by Apple's robust ecosystem lock-in, premium pricing power, steady services revenue growth, and pioneering entry into edge-AI with Apple Intelligence. Despite minor valuation headwinds and regulatory scrutiny in the US and Europe, Apple's exceptionally strong balance sheet, continuous share buybacks, and reliable cash flows provide a highly favorable risk-reward profile for long-term investors.

## Company Overview
Apple Inc. is a global technology leader that designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories, alongside a rapidly growing portfolio of digital services. Apple's primary economic moat is its proprietary ecosystem (iOS, macOS, watchOS), which creates high switching costs for over 2.2 billion active devices. Under the leadership of CEO Tim Cook, the company has transitioned successfully toward a services-heavy model, driving recurring, high-margin revenue from the App Store, Apple Pay, Apple Music, iCloud, and subscription services.

## Financial Analysis
*   **Revenue Growth**: Apple's revenue for the trailing twelve months (TTM) stands at approximately $391.0B, reflecting stable year-over-year growth of 2.5%, driven by iPhone sales resilience and a 12% expansion in the Services division.
*   **Margins**: Operating margin remains exceptionally strong at 30.7%, with gross margin at 46.2% and net margin at 26.3%, demonstrating incredible pricing power and supply-chain efficiency.
*   **Balance Sheet**: Apple maintains a fortress-like balance sheet with $150B+ in cash and marketable securities, offset by $106B in long-term debt. Cash flow from operations exceeds $110B annually.
*   **Valuation**: The stock currently trades at a trailing P/E of 31.5x and a forward P/E of 28.2x, representing a premium to its 5-year historical average but justified by its recurring revenue quality and AI growth optionality.

## News & Sentiment
Market sentiment is highly positive following the progressive rollout of "Apple Intelligence" across its iPhone 16 and M-series Mac lines. Early analyst reports indicate a potential "super-cycle" for iPhone upgrades as consumers seek hardware-accelerated AI features. However, news is partially offset by ongoing anti-trust lawsuits from the US Department of Justice and regulatory pressures in the EU regarding the App Store fee structure, which could lead to minor adjustments in services monetization.

## Risk Assessment
1.  **Regulatory & Antitrust Scrutiny (High)**: Regulatory actions in the EU (DMA compliance) and the US DOJ lawsuit pose a risk to Apple's high-margin Services revenue (specifically App Store commission structures).
2.  **Geopolitical & Supply Chain Concentration (Medium)**: Despite efforts to diversify production to India and Vietnam, Apple remains heavily dependent on Chinese manufacturing and Taiwan's TSMC for advanced silicon.
3.  **Hardware Cycle Stagnation (Low)**: Slow consumer adoption of new hardware upgrades if AI capabilities fail to show immediate utility.

## Competitive Landscape
Apple holds a dominant position in the global premium smartphone market (> $600 segment), capturing over 60% market share. Its main competitor, Samsung, leads in total volume but trails significantly in ecosystem monetization and profit share. Apple's custom silicon (M-series and A-series chips) provides a vertical integration advantage that competitors like Google (Pixel) and Microsoft (Surface) struggle to match in performance-per-watt and consumer hardware-software synergy.

## Growth Outlook
Apple's growth is supported by two primary catalysts:
1.  **AI Hardware Upgrade Cycle**: The replacement cycle of older iPhones to AI-compatible models represents a major TAM expansion over the next 18–24 months.
2.  **Services Expansion**: High-margin subscription services are growing twice as fast as hardware, improving overall corporate margins.
3.  **Wearables and Vision Pro**: Continued development in spatial computing and health-focused wearables (Apple Watch) creates long-term secular growth options.

## Investment Decision
*   **Verdict**: **BUY**
*   **Target Price Horizon**: 12 Months
*   **Bull Case (Target: $260)**: Successful global adoption of Apple Intelligence drives an accelerated double-digit iPhone upgrade cycle, and Services revenue margins exceed 75%, leading to multiple expansion.
*   **Bear Case (Target: $190)**: Regulatory fines force Apple to significantly open iOS to third-party stores globally without fees, eroding Services growth; supply chain disruption in East Asia halts production.
`, 'utf8');

// 6. outputs/company_2.md (Tesla)
fs.writeFileSync(path.join(outputsDir, 'company_2.md'), `# Tesla Inc. (TSLA) — Investment Report

## Executive Summary
Tesla Inc. (TSLA) is rated as a **HOLD** with a confidence level of **70%**. While Tesla's leadership in the global electric vehicle (EV) market and its significant progress in Full Self-Driving (FSD) beta and energy storage are positive, short-to-medium term headwinds remain. High valuation multiples (P/E > 75x), intensifying competition from Chinese EV manufacturers (BYD, Geely), and declining automotive gross margins (ex-credits) suggest that the current stock price fully reflects future growth prospects, limiting immediate upside.

## Company Overview
Tesla Inc. designs, develops, manufactures, sells, and leases fully electric vehicles, energy generation and storage systems, and offers services related to its products. Founded by Martin Eberhard and Marc Tarpenning, and led by CEO Elon Musk, Tesla has built a powerful vertically integrated brand. It operates massive Gigafactories across the US, China, and Europe. Its competitive moat consists of proprietary battery engineering, software integration (FSD), supercharger infrastructure, and manufacturing scale.

## Financial Analysis
*   **Revenue Growth**: Tesla's TTM revenue is approximately $96.8B, representing a moderate growth of 1.2% year-over-year. The slow growth is attributed to price reductions across core Model 3/Y lines to sustain market share.
*   **Margins**: Tesla's automotive gross margin (excluding regulatory credits) has compressed from historical peaks of 25%+ down to 14.6%, reflecting price war pressures. Operating margin stands at 5.8%, with net margin at 8.2%.
*   **Balance Sheet**: Tesla maintains a robust cash reserve of $26B against minimal long-term debt of $5B. Free cash flow generation is volatile but positive, supported by energy storage expansions.
*   **Valuation**: Tesla currently trades at a trailing P/E of 82.4x and a forward P/E of 72.1x. This represents a significant premium to legacy automotive peers, implying the market prices Tesla as a robotics, AI, and software company.

## News & Sentiment
Market sentiment is mixed but highly volatile. Bullish drivers include strong deployment numbers for Tesla's Megapack energy storage units (growing > 100% YoY) and optimism surrounding the upcoming Cybercab/Robotaxi network rollout. However, bearish sentiment is fueled by flat-to-declining delivery growth in key markets like Europe, executive turnover, and political alignments of CEO Elon Musk, which have caused brand polarization among certain consumer demographics.

## Risk Assessment
1.  **Automotive Price Compression (High)**: Intensifying EV price wars globally, especially from low-cost Chinese competitors like BYD, continue to squeeze automotive margins.
2.  **Key Man Risk (High)**: CEO Elon Musk divides his focus among multiple ventures (SpaceX, xAI, Neuralink, X) and his leadership is central to Tesla's premium valuation.
3.  **FSD Regulatory & Technical Hurdles (Medium)**: Delays or regulatory blocks on full Level 4/5 autonomous driving deployment would challenge the core growth thesis.

## Competitive Landscape
Tesla remains the premium EV market leader in North America, but its global lead is contested. BYD surpassed Tesla in total battery EV volume in several quarters, leveraging low cost structures and vertical battery ownership. Legacy automakers (Hyundai, Ford, Volkswagen) are slowly improving their EV offerings, but Tesla retains a significant advantage in software updates (OTA), powertrain efficiency, and battery thermal management.

## Growth Outlook
Tesla's future growth depends on three strategic vectors:
1.  **FSD Licensing and Robotaxis**: Shifting from vehicle sales to a high-margin autonomous transport network represents a massive TAM expansion.
2.  **Tesla Energy (Megapack/Powerwall)**: Stationary storage deployments are growing rapidly, acting as a crucial revenue and margin diversifier.
3.  **Next-Gen Low Cost Vehicle ($25k Model)**: Launching a highly automated, low-cost platform is essential to unlock volume growth in emerging markets.

## Investment Decision
*   **Verdict**: **HOLD**
*   **Target Price Horizon**: 12 Months
*   **Bull Case (Target: $320)**: Fast regulatory approval of FSD in China and Europe; successful ramp-of a $25k vehicle platform; energy division gross margin matches software (> 50%).
*   **Bear Case (Target: $160)**: Delivery growth turns negative; automotive gross margins compress below 12% ex-credits; FSD development encounters technical plateaus or safety recalls.
`, 'utf8');

// 7. outputs/company_3.md (Nvidia)
fs.writeFileSync(path.join(outputsDir, 'company_3.md'), `# NVIDIA Corporation (NVDA) — Investment Report

## Executive Summary
NVIDIA Corporation (NVDA) is recommended as a **STRONG BUY** with a confidence rating of **90%**. NVIDIA commands a near-monopoly (> 90%) in the high-performance AI chip market (GPUs), fueled by insatiable global demand for AI model training and inference. The company's exceptional revenue hyper-growth (> 100% YoY), industry-leading gross margins (> 75%), and deep proprietary software moat (CUDA platform) make it the primary beneficiary of the global generative AI infrastructure buildout. Although valuation multiples are high, they are fully supported by explosive earnings growth.

## Company Overview
NVIDIA Corporation pioneered GPU-accelerated computing. Initially focusing on PC graphics (GeForce), NVIDIA transformed into a dominant compute platform company. Led by visionary CEO Jensen Huang, NVIDIA's competitive moat is not just hardware performance, but its proprietary **CUDA** software ecosystem, which millions of developers use to build AI applications. This creates massive switching costs, as developers cannot easily run CUDA-compiled code on competing hardware from AMD or Intel.

## Financial Analysis
*   **Revenue Growth**: NVIDIA's TTM revenue is approximately $96.3B, representing an astronomical growth of 195% year-over-year, driven entirely by its Data Center segment (H100/H200 and Blackwell chip sales).
*   **Margins**: Gross margin sits at a staggering 76.0%, with operating margin at 54.1% and net margin at 48.8%. These figures are unprecedented for a large-scale hardware developer, highlighting extreme pricing power.
*   **Balance Sheet**: NVIDIA holds a clean balance sheet with $34.8B in cash against just $8.5B in long-term debt. Cash flow from operations grew to over $45B annually.
*   **Valuation**: NVDA trades at a trailing P/E of 65.2x and a forward P/E of 34.5x. The sharp drop in forward P/E highlights that earnings are growing so rapidly that the current price is highly reasonable on a PEG (Price/Earnings-to-Growth) basis.

## News & Sentiment
Market sentiment is overwhelmingly bullish, focused heavily on the rollout of the next-generation "Blackwell" architecture (B200/GB200). CEO Jensen Huang recently noted that demand for Blackwell is "insane," and capacity is fully booked for several quarters. Positive sentiment is slightly tempered by supply constraints from foundry partner TSMC (specifically CoWoS packaging capacity) and export restrictions imposed by the US government on shipping high-end silicon to China.

## Risk Assessment
1.  **Supply Chain Concentration (High)**: NVIDIA is entirely dependent on TSMC for chip fabrication and advanced packaging. Any geopolitical tension in the Taiwan Strait represents a single-point-of-failure risk.
2.  **Customer Concentration (Medium)**: A handful of hyperscalers (Microsoft, Meta, Google, Amazon) account for over 40% of NVIDIA's revenue. Any slowdown in their capital expenditure (CapEx) budgets would impact order rates.
3.  **Competition (Low)**: Competitors like AMD (MI300 series) and custom chips (ASICs) by hyperscalers (TPUs, Trainium) are growing, but NVIDIA's software moat remains a significant barrier.

## Competitive Landscape
NVIDIA faces nominal competition in training deep learning models. AMD's ROCm software layer is catching up to CUDA, but CUDA has a 15-year head start and is deeply integrated into AI frameworks like PyTorch and TensorFlow. Intel's Gaudi chips represent a lower-cost alternative but lag in raw performance and developer ecosystem mindshare.

## Growth Outlook
NVIDIA's growth catalysts over the next 3–5 years include:
1.  **Blackwell Architecture Launch**: Ramp-up of the GB200 platform will drive immediate revenue growth and average selling price (ASP) increases.
2.  **Sovereign AI**: Governments worldwide (Europe, Middle East, Asia) are investing in building domestic AI clusters, creating a secondary customer base outside of US hyperscalers.
3.  **Enterprise & Omniverse**: Expansion of AI deployment into traditional industries (healthcare, automotive, manufacturing) and digital twins using NVIDIA Omniverse.

## Investment Decision
*   **Verdict**: **STRONG BUY**
*   **Target Price Horizon**: 12 Months
*   **Bull Case (Target: $175)**: Blackwell production runs smoothly with zero delays; customer CapEx budgets increase through 2027; sovereign AI demand offsets any domestic cooling.
*   **Bear Case (Target: $95)**: TSMC manufacturing experiences technical yields issues with Blackwell; hyperscalers pause CapEx growth to digest existing capacity; further US export bans restrict NVDA from major Asian markets.
`, 'utf8');

// Copy screenshots
if (fs.existsSync(brainDir)) {
  const files = fs.readdirSync(brainDir);
  const landingPageFile = files.find(f => f.startsWith('landing_page') && f.endsWith('.png'));
  const authPageFile = files.find(f => f.startsWith('auth_page') && f.endsWith('.png'));
  const progressPageFile = files.find(f => f.startsWith('analysis_progress_1') && f.endsWith('.png'));

  if (landingPageFile) {
    fs.copyFileSync(path.join(brainDir, landingPageFile), path.join(screenshotsDir, '01_landing_page.png'));
  }
  if (authPageFile) {
    fs.copyFileSync(path.join(brainDir, authPageFile), path.join(screenshotsDir, '02_auth_page.png'));
  }
  if (progressPageFile) {
    fs.copyFileSync(path.join(brainDir, progressPageFile), path.join(screenshotsDir, '03_analysis_progress.png'));
  }
}

console.log('Assignment folders recreated successfully.');
